const CONFIG = {
  github: {
    username: 'OmegaCrimson',
  },
  base: '/',
  projects: {
    github: {
      display: true,
      header: 'GitHub Projects | مشاريع جيت هاب',
      mode: 'automatic',
      automatic: {
        sortBy: 'stars',
        limit: 8,
        exclude: {
          forks: true,
          projects: [],
        },
      },
      manual: {
        projects: [],
      },
    },
    external: {
      header: 'My Projects | مشاريعي',
      projects: [
        {
          title: 'College Manager | مدير الكلية',
          description: 'College Manager for managing students and grades. | مدير الكلية لإدارة الطلاب والدرجات.',
          imageUrl: 'https://i.ibb.co/ymF8qn4m/banner-square.png',
          link: 'https://nightangel5.gumroad.com/l/collegemanager',
        },
      ],
    },
  },
  seo: {
    title: 'Portfolio of Mohamed Gonem | محفظة محمد غنيم',
    description:
      'Indie developer and systems technologist building cross-platform tools in Python, C#, and Flask. Creator of Student Grader and College Manager. Passionate about UI polish, workflow automation, and developer experience. | مطور مستقل وتقني نظم يبني أدوات متعددة المنصات باستخدام بايثون وC# وFlask. مبتكر Student Grader وCollege Manager. شغوف بتحسين واجهات المستخدم وأتمتة سير العمل وتجربة المطور.',
    imageURL: 'https://avatars.githubusercontent.com/u/yourGitHubID?v=4',
  },
  social: {
    linkedin: 'crimsonnls',
    x: '',
    mastodon: 'MohamedGonem@mastodon.social',
    researchGate: '',
    facebook: 'MohamedGonemCNL',
    instagram: 'crimson_cnl',
    reddit: '0megaCrimson',
    threads: '',
    youtube: 'MohamedGonemCNL',
    udemy: '',
    dribbble: '',
    behance: '',
    medium: '',
    dev: '@mohamedgonem',
    stackoverflow: '',
    discord: 'oscrimson',
    telegram: '@myg_crimson',
    website: '',
    phone: '+201210068442',
    email: 'crimson_cnl@proton.me',
  },
  resume: {
    fileUrl: '',
  },
  skills: [
    'Python | بايثون',
    'Flask | فلاسْك',
    'C# | سي شارب',
    '.NET | دوت نت',
    'Blazor | بلازور',
    'WinForms | وين فورمز',
    'Node.js | نود جي إس',
    'Godot Engine (4.4) | محرك جودو',
    'Semantic Release | إصدار دلالي',
    'PowerShell (PS1) | باورشيل',
    'VB 6.0 | فيجوال بيسك 6.0',
    'C Programming | لغة C',
    'Git & GitHub | جيت وجيت هاب',
    'CI/CD | التكامل والتسليم المستمر',
    'PyInstaller | باي إنستولر',
    'Inno Setup | إعداد إينو',
    'Excel | إكسل',
    'Word | وورد',
    'PowerPoint | باوربوينت',
    'Access 2003 | أكسس 2003',
    'SQL | إس كيو إل',
    'Cybersecurity Fundamentals | أساسيات الأمن السيبراني',
    'Digital Hygiene | النظافة الرقمية',
    'Threat Awareness | الوعي بالتهديدات',
    'Data Protection | حماية البيانات',
    'Packet Tracer | باكيت ترايسر',
    'Routing & Switching | التوجيه والتبديل',
    'WAN Technologies | تقنيات الشبكات الواسعة',
    'Windows Server 2003 | ويندوز سيرفر 2003',
    'Workflow Automation | أتمتة سير العمل',
    'Debugging & Error Tracing | تصحيح وتتبع الأخطاء',
    'Open Source Etiquette | آداب المصدر المفتوح',
    'Documentation & README Design | التوثيق وتصميم ملفات README',
    'System Analysis | تحليل الأنظمة',
    'Logic Gates | بوابات منطقية',
    'Computer Maintenance & Upgrades | صيانة وترقية الحواسيب',
    'Microprocessors & Microcontrollers | المعالجات الدقيقة والمتناهية',
    'Office Applications | تطبيقات أوفيس',
  ],
  experiences: [
    {
      company: 'The Holding Company for Water and Wastewater | الشركة القابضة لمياه الشرب والصرف الصحي',
      position: 'Operating Technician | فني تشغيل',
      from: 'October 2023 | أكتوبر 2023',
      to: 'Present | حتى الآن',
      companyLink: 'https://www.hcww.com.eg',
    },
    {
      company: 'Indie Developer & Founder | مطور مستقل ومؤسس',
      position: 'Solo Developer / Product Builder | مطور منفرد / منشئ منتجات',
      from: '2024',
      to: 'Present | حتى الآن',
      companyLink: 'https://github.com/OmegaCrimson',
    },
  ],
  certifications: [
    {
      name: 'Foundational C# Certification | شهادة أساسيات C#',
      body: 'A verified certification covering core C# programming concepts... | شهادة معتمدة تغطي مفاهيم البرمجة الأساسية بلغة C#...',
      year: 'November 2025 | نوفمبر 2025',
      link: 'https://www.freecodecamp.org/certification/fcc-53810a4a-4cd4-41d1-9e18-1f3d18d58e08/foundational-c-sharp-with-microsoft',
    },
    {
      name: 'Getting Started with Cybersecurity – IBM SkillsBuild | مقدمة في الأمن السيبراني – IBM SkillsBuild',
      body: 'An introductory course on cybersecurity principles... | دورة تمهيدية حول مبادئ الأمن السيبراني...',
      year: '2025',
      link: 'https://www.credly.com/badges/6838fcfb-8fef-4e04-9d6d-1fb0a8d88366/public_url',
    },
    {
      name: 'Introduction to Cybersecurity – Cisco | مقدمة في الأمن السيبراني – سيسكو',
      body: 'A recognized certification covering the fundamentals... | شهادة معترف بها تغطي أساسيات الأمن السيبراني...',
      year: 'November 2025 | نوفمبر 2025',
      link: 'https://www.credly.com/badges/6f7af68b-879a-43ad-8792-703c50fc6852/public_url',
    },
    {
      name: 'Cybersecurity Fundamentals – IBM SkillsBuild | أساسيات الأمن السيبراني – IBM SkillsBuild',
      body: 'Covers essential cybersecurity concepts... | تغطي مفاهيم الأمن السيبراني الأساسية...',
      year: '2025',
      link: 'https://www.credly.com/badges/f4079f07-66a8-4841-a771-51a9fc568c9b/public_url',
    },
    {
      name: 'Digital Literacy – IBM SkillsBuild | الثقافة الرقمية – IBM SkillsBuild',
      body: 'Introduces foundational digital skills... | يقدم مهارات رقمية أساسية...',
      year: '2025',
      link: 'https://www.credly.com/badges/7a755616-347d-4085-a606-24fd28497637/public_url',
    },
    {
      name: 'Digital Mindset – IBM SkillsBuild | التفكير الرقمي – IBM SkillsBuild',
      body: 'Explores the mindset and skills needed... | يستكشف العقلية والمهارات اللازمة للنجاح في العالم الرقمي...',
      year: '2025',
      link: 'https://www.credly.com/badges/1e24dbad-ea08-402e-8e4f-4e2672c1d28d/public_url',
    },
  ],
  educations: [],
  publications: [],
  blog: {
    source: 'dev',
    username: '',
    limit: 2,
  },
  googleAnalytics: {
    id: 'G-MBV5ZKNHE8',
  },
  hotjar: { id: '', snippetVersion: 6 },
  themeConfig: {
    defaultTheme: 'business',
    disableSwitch: false,
    respectPrefersColorScheme: false,
    displayAvatarRing: true,
    themes: [
      'light',
      'dark',
      'black',
      'luxury',
      'dracula',
      'business',
      'night',
      'abyss',
    ],
  },
  enablePWA: true,
};

export default CONFIG;